os:
  openCommand: "vim {{filename}}"
gui:
  sidePanelWidth: 0.2
  commandLogSize: 4
  scrollPastBottom: false
notARepository: "skip"
# git:
#   paging:
#     colorArg: always
#     pager: delta --dark --paging=never
