format = """
$jobs\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$status\
$character"""

command_timeout = 1001

[character]
vicmd_symbol = "[](bold yellow)"

