#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_gap 06

# yabai -m rule --add app="^Spotify$" manage=off
# yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off

